### PR TITLE
Fix for i18n

### PR DESCRIPTION
**Pull request by cxgreat2014**
before:

image

after:

image
:+1:

### CODE REVIEW

**Comment by purplesyringa** [comment]
For such parsing, there is `decodeUTF8` function which does the same as `decodeURIComponent(escape(string))`. So, you could simply replace `arrayToString` with `decodeUTF8`.

Anyway, thanks for reporting!

**Comment by ghost** [comment]
I now have problems with seeing diffs. Looks like it could be from this(decodeUTF8)?

```
Uncaught (in promise) URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Git.decodeUTF8 (git.js:124)
    at then.b (repo.js:814)
    at <anonymous>
```

**Comment by cxgreat2014** [comment]
Edited, thanks for you advice :smiley:

**Comment by purplesyringa** [comment]
Merged, thanks!

**Comment by purplesyringa** [comment]
@krixano: Were any binary files added during that diff?

**Comment by ghost** [comment]
@imachug I got the error for diffs of all commits. I don't think I have any binary files in my repo.

I don't have the problem anymore though.

**Pull request merged**
